apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter
  labels:
    app: twitter
spec:
  selector:
    matchLabels:
      app: twitter
  template:
    metadata:
      labels:
        app: twitter
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/twitter-sink:v1
          name: twitter
